### ISSUE TITLE
Configurable time-elapsed parser(s)

### ISSUE THREAD

**Issue by j-mai** [xmidt-org/glaukos#34]
Currently, the boot-time metric parser measures the time it takes for a CPE to go offline and start up again. Instead, we want three different boot-time parsers to measure the different stages of the boot-up process.

To allow for the possibility of easily adding similar parsers in the future, we should make a `TimeElapsedParser` that can be configured to calculate the time between two different event types: one trigger event and one previous event to look for.

Note that in some cases, we may only need one event. Some calculations only require us to take the difference between the birthdate and boot-time of the event.

Upon creating the time-elapsed parser, we need to make sure that metrics won't clash if we happen to have the same names for multiple parsers.

**Comment by kristinaspring** [comment]
When making this configurable `TimeElapsedParser`, we can also add a configurable option for the type of validation to do against the event history.  This relies upon https://github.com/xmidt-org/interpreter/issues/9 being done.  An example of what configuration for a `TimeElapsedParser` could look like:
```yaml
    - name: "reboot_to_manageable"
      searchedEvent:
        regex: ".*/reboot-pending/"
        calculateUsing: "birthdate"
      incomingEvent:
        regex: ".*/fully-manageable/"
        calculateUsing: "birthdate"
      historyValidation: "full-timeline"
```
