### ISSUE TITLE
Configurable event history validation

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/glaukos#52]
This is dependent on work for https://github.com/xmidt-org/glaukos/issues/34 being done.

When making this configurable TimeElapsedParser, we can also add a configurable option for the type of validation to do against the event history. This relies upon xmidt-org/interpreter#9 being done. An example of what configuration for a TimeElapsedParser could look like:

```yaml
    - name: "reboot_to_manageable"
      searchedEvent:
        regex: ".*/reboot-pending/"
        calculateUsing: "birthdate"
      incomingEvent:
        regex: ".*/fully-manageable/"
        calculateUsing: "birthdate"
      historyValidation: "full-timeline"
```
